	
	<div class="top-ribbon" style="margin-top:60px">
		<div class="container">
			<div class="row-fluid">
				<div class="span4 top-ribbon-head" style="margin-top:20px;">Terms & Conditions</div>
				<div class="span8"></div>
			</div>
		</div>
	</div>
	
	<div class="container">
		<div class="row-fluid">
			<div class="inner-body">
				The User of the web-site (hereinafter referred to as "User") must carefully read and agree to the following terms and conditions, including any future amendments (hereinafter collectively referred to as the "Terms & Conditions") before using the web-site www.ahaguru.com (hereinafter referred to as "web-site"). By using the web-site Users are accepting to be bound by the provisions of these terms & conditions, the privacy policy of the AhaGuru Education Technology Private Limited (hereinafter referred to as "AGET") and disclaimer by AGET.
<ol>
	<li>These Terms and Conditions and the Privacy Policy Statement which are hereby incorporated as if set forth fully herein, represent the complete agreement between you and the Company for the use of and access to the Services and/or other contents of this website.</li>
	<li>At the time of registration the User must be at least eighteen years old. AGET reserves the right to refuse service/registration to any person at any point of time without giving any prior notice and without assigning any reason whatsoever.</li>
	<li>User agrees that the services once subscribed to by the User are not refundable and all amount(s) paid shall stand appropriated.</li>
	<li>Nothing in this Agreement shall be deemed to confer any third-party rights or benefits.</li>
	<li>AGET authorizes User to view and access the content available on or from the web-site solely for their personal use. The contents of the web-site and of all other websites under AGET's control, whether partial or otherwise such as text, videos, graphics, images, logos, button icons, software and other contents as well as compilation of contents (meaning the collection, arrangement and assembly), are property of AGET and are protected under both India and foreign copyright, trademark and other laws. Unauthorized use of such Content will be violation of copyright, trademark and other intellectual property rights of AGET. User may not sell or modify the said content or reproduce, display, publicly perform, distribute, or otherwise use such Content in any way for any public or commercial purpose. The use of the AGET's Content on any other web site or in a networked computer environment for any purpose is prohibited. User shall not copy or adapt the AGET code that the AGET creates to generate any Content or the pages making up any of its web-site which is also protected by the AGET's copyright.</li>
	<li>User shall be solely responsible for maintaining the confidentiality of their account and passwords. The User shall be solely responsible for all activities happening under his/her Username whether authorized or not. User agrees to immediately notify the Company of any unauthorized use of your Account and Password.</li>
	<li>AGET reserves the right to modify, suspend, cancel, discontinue or terminate the Services of the web-site or reject any or all entries/blogs at their absolute discretion without giving any prior notice and without assigning any reason whatsoever and without any liability to the User.</li>
	<li>User shall be responsible for use of the web-site, for any entries/posts/blog that he/she uploads/makes, and for any consequences arising thereof. The User agrees that he/she shall use the web-site in accordance with all laws, rules and regulations, as applicable from time to time, including without limitation IT laws and laws relating to unfair competition, antidiscrimination, false advertising and defamation. The User further agrees that the usage of web-site by the User shall not violate any third party rights including but not limited to Intellectual Property Rights, Right of Privacy and Right of Publicity. In addition to above, the User agrees that User shall not use web-site in order to transmit, distribute, store or destroy material, including without limitation AGET's content, that is defamatory, obscene, threatening, abusive or hateful. Any violation of any of the foregoing, including the terms and conditions mentioned herein shall result in immediate termination of this Agreement, Moreover, AGET reserves the right to seek damages from any such User to the extent permitted by law.</li>
	<li>Users are also prohibited from violating or attempting to violate the security of web-site, including, without limitation the following activities: (a) accessing data not intended for such User or logging into a server or account which the User is not authorized to access; (b) attempting to probe, scan or test the vulnerability of a system or network or to breach security or authentication measures without proper authorization; (c) attempting to interfere with service to any User, host or network, including, without limitation, via means of submitting a virus to web-site, overloading, "flooding", "spamming", "mailbombing" or "crashing"; or (d) forging any TCP/IP packet header or any part of the header information in any e-mail or newsgroup posting. Violations of system or network security may result in civil or criminal liability. The Company will investigate occurrences which may involve such violations and may involve, and cooperate with, law enforcement authorities in prosecuting Users who are involved in such violations.</li>
	<li>The contents of specific postings made by the User are posted and are the responsibility of the User who makes such postings. Though AGET reserves the right to filter out postings which may carry offensive, harmful, inaccurate, pornographic content or content which infringes on the Intellectual Property Rights of any third party or any rights of publicity or privacy or is defamatory, libellous, threatening or harassing or is indecent and contains any viruses, trojans, trap doors, back doors, easter eggs, worms, time bombs, cancelbots or other computer programming routines that are intended to damage, detrimentally interfere with, surreptitiously intercept or expropriate any system, data or personal information or otherwise inappropriate content, it does not take any responsibility for such content and/or for deceptive, mislabelled or defamatory content. AGET merely provides a platform to access the content posted by the Users by using the Services of the web-site. The Users are expected to take necessary precautions and comply with various provisions of laws while uploading any contents on the web-site.</li>
	<li>However, AGET specifically prohibits the posting of User's content which provides the following and/or has the effect of the following. The list below is for illustration only and is not a complete list of all prohibited User Content. The User Content:- 11.1) is implicitly or explicitly offensive, such as User Content that engages in, endorses or promotes racism, bigotry, hatred or physical harm of any kind against any group or individual;11.2) harasses, incites harassment or advocates harassment of another group or individual; 11.3) involves the transmission of "junk mail", "chain letters," or unsolicited mass mailing or "spamming"; 11.4) promotes or endorses false or misleading information or illegal activities or conduct that is abusive, threatening, obscene, defamatory, libellous or which amounts to contempt of any judicial authority;11.5) promotes or endorses an illegal or unauthorized use of any copyrighted work, such as providing or making available pirated computer programs or links to them, providing or making available information to circumvent manufacture-installed copy-protect devices, or providing or making available pirated music or other media or links to pirated music or other media files; 11.6) contains restricted or password only access pages, or hidden pages or images;11.7) displays or links to obscene, indecent pornographic, material of any kind; 11.8) provides instructional information about illegal activities or other activities prohibited by these Terms, including without limitation, making or buying illegal weapons, violating someone's privacy, or provides or creates computer viruses or pirating any media; and solicits passwords or personal identifying information from other Users;</li>
	<li>The contents, views and ideas expressed/posted are of the respective Users and AGET does not support/endorse any such views, ideas and expressions. Moreover, AGET does not represent or guarantee the truthfulness, accuracy, or reliability of any such postings/blogs posted by the Users, the ability of employers to offer job opportunities to candidates or the ability of candidates to fill job openings or any User Content and makes no representations about any jobs, resumes or User Content on the web-site and the Users are cautioned to use common sense and proper judgment in this regard. AGET is not involved in the actual transaction between employers and candidates. Any reliance on the content posted by other Users using the web-site shall be entirely at the risk of the User. User assumes all risks, including but not limited to the risk of physical harm, of dealing with strangers, foreign nationals, underage persons or people acting under false.</li>
	<li>AGET reserves the right without prior notice to access, read preserve and/or disclose the personal information of the User including the content of the postings/blogs if the same is required: 13.1) in order to comply with any court judgment/decree/order/directive,13.2) by any legal/government authority;13.3) by applicable law;13.4) by professional/legal advisers, directors, employees/agents/representatives of AGET in connection with this Agreement or otherwise;13.5) for investigating potential violations of the terms herein or applicable national & international laws;13.6) for investigating deliberate damage to the Services or its legitimate operation;13.7) for responding to service support requests, or13.8) for protecting the rights, property or safety of AGET and/or its Directors, employees and the general public at large.</li>
	<li>AGET reserves the right to store and process the personal information provided by the User in India or any other country where AGET or its agents/representatives/group companies maintain storage and processing facilities and the User by using the services herein consents to any such transfer of information outside India without prior notice.</li>
	<li>AGET shall not be liable or responsible in any manner whatsoever for deletion and/or failure to transmit or store any postings/blogs posted by the User by using the Services herein or personal information provided by the User or any other communication maintained by the Service. Further, AGET reserves the right to create limits on use of the said Service and storage at its sole discretion without assigning any reason whatsoever and without giving any prior notice.</li>
	<li>AGET does not warrant that web-site will operate without any technical error and is free from any computer viruses or other harmful mechanisms. AGET shall not be liable in any manner whatsoever for any consequences, claims, damages, costs etc. arising out of any of the above-said reasons or due to any force majure factors and/or due to any reasons beyond the control of AGET. AGET to the fullest extent permitted by law, disclaims all warranties, whether express or implied, including the warranty of merchantability, fitness for particular purpose and non-infringement. AGET makes no warranties about the accuracy, reliability, completeness, or timeliness of the content, services, software, text, graphics, and links used on the web-site.</li>
	<li>AGET's maximum liability arising out of or in connection with the web-site or your use of the AGET's content, regardless of the cause of action (whether in contract, tort, breach of warranty or otherwise), will not exceed Rs. 50,000/</li>
	<li>AGET shall not be responsible or liable in any manner whatsoever for the exercise or non-exercise of its rights herein.</li>
	<li>All AGET trade names, trademarks, logos, domain names including without limitation www.ahaguru.com, all content on Ahaguru.com, are the exclusive property of AGET and the User shall not use the same without the prior written permission of AGET.</li>
	<li>AGET reserves the right in its sole discretion to investigate and take legal action against anyone who engages in any illegal or prohibited conduct or otherwise violates these Terms of Use, including without limitation, removing the User Content from the web-site and/or terminating the offending User's ability to access the web-site and/or use AGET's services. AGET may take any other action with respect to User Content or User actions that it deems necessary or appropriate in its sole discretion if it believes it may create liability for the AGET or may cause the AGET to lose (in whole or in part) the services of its ISPs or other suppliers.</li>
	<li>The User agrees to indemnify AGET and its directors, employees and agents against any third party claim, action, suit or proceeding resulting from his use of the Services herein or arising out of the Content submitted, posted, transmitted or otherwise made available by the User while using the web-site, or use of the web-site by the User in violation of these terms & conditions or violation of any third party rights by the User.</li>
	<li>AGET reserves the right, in its sole discretion, to amend or revise these terms & conditions at any point of time, without prior notice and the User agrees to be bound by such amendments or revisions. It is therefore suggested that the User must periodically review the updated version of these terms & conditions at www.ahaguru.com.</li>
	<li>All the disputes arising between the User and AGET is to be governed by and construed in accordance with the laws of India. The Courts/Tribunals at Chennai, Tamil Nadu shall have the exclusive jurisdiction over any disputes relating to the subject matter of this Agreement.</li>
</ol>
	</div>
		</div>
	</div>
	
